// Package account manages principals from an administrative view: listing every
// user and agent, creating human users, and disabling/enabling users. A
// "principal" is a store.User — a human (AgentOfID == "") or an agent. Disabling
// is a soft delete: the row and all its attribution stay, but the user can no
// longer authenticate (enforced in the session, token, and login paths).
package account

import (
	"context"
	"errors"
	"regexp"

	"github.com/peios/acta/internal/authn/local"
	"github.com/peios/acta/internal/store"
)

var (
	ErrInvalidUsername = errors.New("account: invalid username")
	ErrWeakPassword    = errors.New("account: password too short")
	ErrLastActiveUser  = errors.New("account: cannot disable the last active user")
	ErrNotHuman        = errors.New("account: only user accounts can be disabled")
)

// usernameRe constrains a human username to lowercase alphanumerics plus dot,
// underscore and hyphen, starting alphanumeric. No slash — that's the agent
// handle separator ("owner/agent") — and no spaces.
var usernameRe = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]{0,39}$`)

type Service struct {
	store store.Store
}

func New(st store.Store) *Service { return &Service{store: st} }

// List returns every principal — humans and agents — display-sorted.
func (s *Service) List(ctx context.Context) ([]store.User, error) {
	return s.store.ListUsers(ctx)
}

func (s *Service) Get(ctx context.Context, id string) (store.User, error) {
	return s.store.UserByID(ctx, id)
}

// Create makes a new human user with an initial password (typed or generated by
// the caller); the password is validated and hashed here.
func (s *Service) Create(ctx context.Context, username, display, password string) (store.User, error) {
	uname := local.NormalizeUsername(username)
	if !usernameRe.MatchString(uname) {
		return store.User{}, ErrInvalidUsername
	}
	if display == "" {
		display = uname
	}
	if err := local.ValidatePassword(password); err != nil {
		return store.User{}, ErrWeakPassword
	}
	hash, err := local.HashPassword(password)
	if err != nil {
		return store.User{}, err
	}
	return s.store.CreateUser(ctx, store.NewUser{Username: uname, Display: display, PasswordHash: hash})
}

// Disable soft-deletes a human user. Agents can't be disabled here, and the
// last remaining active human can't be disabled (a lockout guard that also
// protects the bootstrap admin).
func (s *Service) Disable(ctx context.Context, id string) error {
	u, err := s.store.UserByID(ctx, id)
	if err != nil {
		return err
	}
	if u.AgentOfID != "" {
		return ErrNotHuman
	}
	users, err := s.store.ListUsers(ctx)
	if err != nil {
		return err
	}
	active := 0
	for _, x := range users {
		if x.AgentOfID == "" && x.DisabledAt == nil {
			active++
		}
	}
	if active <= 1 {
		return ErrLastActiveUser
	}
	return s.store.SetUserDisabled(ctx, id, true)
}

// Enable clears a user's disabled flag.
func (s *Service) Enable(ctx context.Context, id string) error {
	u, err := s.store.UserByID(ctx, id)
	if err != nil {
		return err
	}
	if u.AgentOfID != "" {
		return ErrNotHuman
	}
	return s.store.SetUserDisabled(ctx, id, false)
}
